services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: $DATABASE_PASSWORD
      MYSQL_DATABASE: $DATABASE_NAME
      MYSQL_USER: $DATABASE_USER
      MYSQL_PASSWORD: $DATABASE_PASSWORD
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306